
const AuditPage = () => {
  return (
    <div className="block active">
      <div className="mb-6 flex flex-wrap items-start justify-between gap-3 max-[768px]:flex-col max-[768px]:items-stretch max-[768px]:gap-4">
    <div className="[&_h1]:text-xl [&_h1]:font-bold [&_h1]:text-slate-950 [&_p]:mt-1 [&_p]:text-[12.5px] [&_p]:text-slate-500"><h1>Audit Log</h1><p>Immutable activity trail · AES-256 field-level encryption</p></div>
    <div className="flex flex-wrap gap-2 max-[768px]:w-full [&_.btn]:max-[768px]:w-full [&_.btn]:max-[768px]:justify-center">
      <button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-white text-slate-700 hover:border-blue-800 hover:text-blue-800"><svg viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7,10 12,15 17,10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>Export Log</button>
    </div>
  </div>
  <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5">
    <div className="mb-4 flex items-center justify-between gap-2"><div><div className="text-[15px] font-bold text-slate-950">Event Stream</div><div className="mt-0.5 text-xs text-slate-500">All system actions · All roles · Real-time</div></div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--err)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">BREACH ALERT — Transit T-07 temperature exceeded 8°C</div><div className="mt-0.5 text-[11px] text-slate-400">System · Transfer ticket quarantined · Webhook sent to admin · Batch RX-1044-E flagged</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 13 · 10:47</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--p)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">GS1 Scan — TZ-2204-A verified clean (Pharm. Usman)</div><div className="mt-0.5 text-[11px] text-slate-400">Role A · GTIN 0304817892 · LUTH · WAOAB Security cleared</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 13 · 10:31</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--ok)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">Transfer approved — Trastuzumab ×4 (Dr. Okonkwo)</div><div className="mt-0.5 text-[11px] text-slate-400">Role C · Lagos Island GH → LASUTH · transfer_ticket #T-094</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 13 · 09:55</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--p)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">Prescription sent to network — Patient #0492</div><div className="mt-0.5 text-[11px] text-slate-400">ICD-10 C50.4 · AXA Mansard · Trastuzumab ×2 · Clinical JSON packaged</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 13 · 09:30</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--warn)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">Near-expiry flag — RX-0912-A (32 days remaining)</div><div className="mt-0.5 text-[11px] text-slate-400">System · item_status set to near_expiry · Broadcast to 6 recipient hubs within 50 miles</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 13 · 08:00</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--ok)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">Stock ingested — 15 vials Trastuzumab (Pharm. Nwosu)</div><div className="mt-0.5 text-[11px] text-slate-400">Role A · POS webhook · Pharmacy X · Batch TZ-2211-A · Jan 2027</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 12 · 17:10</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--p)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">New facility onboarded — Lagos Island GH</div><div className="mt-0.5 text-[11px] text-slate-400">Role C · Dr. Sotunde · IP whitelist set · 2 devices paired · Role B assigned</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 11 · 11:00</div></div>
    <div className="flex gap-3 border-b border-slate-100 p-3 transition hover:bg-slate-50 last:border-b-0" style={{border: 'none'}}><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full ring-4 ring-slate-100" style={{background: 'var(--ok)'}}></div><div className="flex-1"><div className="text-[12.5px] font-medium text-slate-800">JWT token renewed — Pharm. Usman</div><div className="mt-0.5 text-[11px] text-slate-400">Session sliding-window renewal · EKO Hospital device</div></div><div className="mt-1 shrink-0 text-[11px] text-slate-400">Jun 11 · 09:05</div></div>
  </div>
    </div>
  );
}
export default AuditPage;
