import type React from 'react';

const ExpiryPage: React.FC = () => {
  return (
    <div className="block active">
      <div className="mb-6 flex flex-wrap items-start justify-between gap-3 max-[768px]:flex-col max-[768px]:items-stretch max-[768px]:gap-4">
    <div className="[&_h1]:text-xl [&_h1]:font-bold [&_h1]:text-slate-950 [&_p]:mt-1 [&_p]:text-[12.5px] [&_p]:text-slate-500"><h1>Near-Expiry Alerts</h1><p>Items flagged within 60 days of expiry — auto-broadcast to recipient hubs</p></div>
  </div>

  <div className="mb-6 flex flex-wrap items-start gap-2.5 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-3 text-[12.5px] text-slate-800 [&_p]:min-w-0 [&_p]:flex-1 [&_svg]:h-4 [&_svg]:w-4 [&_svg]:shrink-0 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-amber-500 text-white">
    <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 8v4l3 3"/></svg>
    <p><strong>7 items</strong> require redistribution within the next 60 days to prevent wastage. Facilities within 50-mile radius have been notified.</p>
  </div>

  <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5">
    <div className="mb-4 flex items-center justify-between gap-2"><div><div className="text-[15px] font-bold text-slate-950">Near-Expiry Stock Register</div><div className="mt-0.5 text-xs text-slate-500">Sorted by urgency</div></div></div>
    <div className="overflow-x-auto rounded-xl border border-slate-100 bg-white shadow-lg shadow-slate-900/10 [&_table]:w-full [&_table]:border-separate [&_table]:border-spacing-0 [&_table]:text-[13px] [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-slate-200 [&_th]:bg-slate-100 [&_th]:px-4 [&_th]:py-3.5 [&_th]:text-left [&_th]:text-[11px] [&_th]:font-bold [&_th]:uppercase [&_th]:tracking-[0.5px] [&_th]:text-slate-400 [&_td]:border-b [&_td]:border-slate-100 [&_td]:px-4 [&_td]:py-3.5 [&_td]:align-middle [&_td]:text-slate-700 [&_tr:hover_td]:bg-slate-100 [&_tr:last-child_td]:border-b-0">
      <table>
        <thead><tr><th>Drug</th><th>Lot Number</th><th>Donor Facility</th><th>Qty</th><th>Expiry</th><th>Urgency</th><th>Nearest Recipient</th><th>Action</th></tr></thead>
        <tbody>
          <tr style={{background: 'var(--errl)'}}><td><div className="text-[13px] font-bold text-slate-950">Rituximab</div><div className="mt-0.5 text-[11px] text-slate-400">GTIN 0812945002</div></td><td style={{fontFamily: 'monospace', fontSize: '12px'}}>RX-1044-E</td><td>LASUTH</td><td>7</td><td>Jul 22, 2026</td><td><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-red-50 text-red-700" style={{padding: '4px 10px', border: '1px solid #fecaca'}}>Critical: 26 days</span></td><td>EKO Hospital · 8.1km</td><td><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-blue-800 text-white hover:bg-blue-900" style={{padding: '5px 10px', fontSize: '11px', background: 'var(--err)', border: 'none'}}>Priority Transfer</button></td></tr>
          <tr style={{background: 'var(--errl)'}}><td><div className="text-[13px] font-bold text-slate-950">Rituximab</div><div className="mt-0.5 text-[11px] text-slate-400">GTIN 0812944031</div></td><td style={{fontFamily: 'monospace', fontSize: '12px'}}>RX-0912-A</td><td>EKO Hospital</td><td>5</td><td>Jul 28, 2026</td><td><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-red-50 text-red-700" style={{padding: '4px 10px', border: '1px solid #fecaca'}}>Critical: 32 days</span></td><td>LUTH · 7.8km</td><td><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-blue-800 text-white hover:bg-blue-900" style={{padding: '5px 10px', fontSize: '11px', background: 'var(--err)', border: 'none'}}>Priority Transfer</button></td></tr>
          <tr><td><div className="text-[13px] font-bold text-slate-950">Trastuzumab</div><div className="mt-0.5 text-[11px] text-slate-400">GTIN 0304817892</div></td><td style={{fontFamily: 'monospace', fontSize: '12px'}}>TZ-2204-B</td><td>LUTH</td><td>8</td><td>Aug 3, 2026</td><td><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-amber-50 text-amber-700" style={{padding: '4px 10px'}}>Warning: 38 days</span></td><td>Lagos Island GH · 14.2km</td><td><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-blue-800 text-white hover:bg-blue-900" style={{padding: '5px 10px', fontSize: '11px'}}>Request Transfer</button></td></tr>
          <tr><td><div className="text-[13px] font-bold text-slate-950">Pertuzumab</div><div className="mt-0.5 text-[11px] text-slate-400">GTIN 0321847920</div></td><td style={{fontFamily: 'monospace', fontSize: '12px'}}>PT-0707-D</td><td>Lagos Island GH</td><td>3</td><td>Sep 5, 2026</td><td><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-amber-50 text-amber-700" style={{padding: '4px 10px'}}>Warning: 41 days</span></td><td>LUTH · 14.2km</td><td><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-blue-800 text-white hover:bg-blue-900" style={{padding: '5px 10px', fontSize: '11px'}}>Request Transfer</button></td></tr>
          <tr><td><div className="text-[13px] font-bold text-slate-950">Bevacizumab</div><div className="mt-0.5 text-[11px] text-slate-400">GTIN 0519273447</div></td><td style={{fontFamily: 'monospace', fontSize: '12px'}}>BV-1103-C</td><td>UCH Ibadan</td><td>12</td><td>Sep 12, 2026</td><td><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-amber-50 text-amber-700" style={{padding: '4px 10px'}}>Warning: 48 days</span></td><td>LASUTH · 22km</td><td><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-blue-800 text-white hover:bg-blue-900" style={{padding: '5px 10px', fontSize: '11px'}}>Request Transfer</button></td></tr>
        </tbody>
      </table>
    </div>
  </div>
    </div>
  );
}

export default ExpiryPage;
