import { ModalId, PageId } from "../../lib/types";



import type React from 'react';
interface UsersPageProps {
  onNav: (id: PageId) => void;
  onOpenModal: (id: ModalId) => void;
}

const UsersPage: React.FC<UsersPageProps> = ({ onNav, onOpenModal }) => {
  return (
    <div className="block active">
      <div className="mb-6 flex flex-wrap items-start justify-between gap-3 max-[768px]:flex-col max-[768px]:items-stretch max-[768px]:gap-4">
    <div className="[&_h1]:text-xl [&_h1]:font-bold [&_h1]:text-slate-950 [&_p]:mt-1 [&_p]:text-[12.5px] [&_p]:text-slate-500"><h1>User Management</h1><p>Role-based access control · Three-tier RBAC system</p></div>
    <div className="flex flex-wrap gap-2 max-[768px]:w-full [&_.btn]:max-[768px]:w-full [&_.btn]:max-[768px]:justify-center"><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 bg-blue-800 text-white hover:bg-blue-900" onClick={() => onOpenModal('modal-user')}><svg viewBox="0 0 24 24"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Add User</button></div>
  </div>

  <div className="grid grid-cols-3 gap-4 max-[768px]:grid-cols-1" style={{marginBottom: '1rem'}}>
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5" style={{borderTop: '3px solid var(--p)'}}><div className="mb-4 flex items-center justify-between gap-2"><div><div className="text-[15px] font-bold text-slate-950">Role A — Submitting Pharmacist</div></div></div><p style={{fontSize: '12px', color: 'var(--g500)', marginBottom: '10px'}}>Scan GS1, log inventory, flag surplus stock</p><div className="text-2xl font-bold text-slate-950" style={{fontSize: '22px', marginBottom: '0'}}>14</div></div>
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5" style={{borderTop: '3px solid var(--ac)'}}><div className="mb-4 flex items-center justify-between gap-2"><div><div className="text-[15px] font-bold text-slate-950">Role B — Requesting Pharmacist</div></div></div><p style={{fontSize: '12px', color: 'var(--g500)', marginBottom: '10px'}}>View availability, raise stock-out alerts, request transfers</p><div className="text-2xl font-bold text-slate-950" style={{fontSize: '22px', marginBottom: '0'}}>18</div></div>
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5" style={{borderTop: '3px solid var(--ok)'}}><div className="mb-4 flex items-center justify-between gap-2"><div><div className="text-[15px] font-bold text-slate-950">Role C — Network Admin</div></div></div><p style={{fontSize: '12px', color: 'var(--g500)', marginBottom: '10px'}}>Verify facilities, audit logs, approve transfers</p><div className="text-2xl font-bold text-slate-950" style={{fontSize: '22px', marginBottom: '0'}}>3</div></div>
  </div>

  <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5">
    <div className="flex items-center gap-2.5 border-b border-slate-100 py-2.5 last:border-b-0" style={{padding: '12px 0'}}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[11px] font-bold text-white [&_img]:h-full [&_img]:w-full [&_img]:rounded-full [&_img]:object-cover" style={{background: 'var(--p)', width: '40px', height: '40px'}}><img src="https://images.unsplash.com/photo-1559839734-2b71f153678f?w=100&h=100&fit=crop" alt="AO"/></div><div><div className="text-[13px] font-semibold text-slate-800" style={{fontSize: '14px'}}>Dr. Adeola Okonkwo</div><div className="text-[11px] text-slate-400">Role C — Network Admin · <span style={{color: 'var(--p)', fontWeight: '600'}}>LUTH</span></div></div><div className="ml-auto flex gap-1.5"><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-emerald-50 text-emerald-700">Active</span><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-white text-slate-700 hover:border-blue-800 hover:text-blue-800" style={{padding: '4px 12px', fontSize: '11px'}}>Permissions</button><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-800" style={{padding: '4px 8px', fontSize: '11px'}}>Edit</button></div></div>
    <div className="flex items-center gap-2.5 border-b border-slate-100 py-2.5 last:border-b-0" style={{padding: '12px 0'}}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[11px] font-bold text-white [&_img]:h-full [&_img]:w-full [&_img]:rounded-full [&_img]:object-cover" style={{background: 'var(--pd)', width: '40px', height: '40px'}}><img src="https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=100&h=100&fit=crop" alt="BU"/></div><div><div className="text-[13px] font-semibold text-slate-800" style={{fontSize: '14px'}}>Pharm. Bisi Usman</div><div className="text-[11px] text-slate-400">Role A — Submitting Pharmacist · <span style={{color: 'var(--p)', fontWeight: '600'}}>EKO Hospital</span></div></div><div className="ml-auto flex gap-1.5"><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-emerald-50 text-emerald-700">Active</span><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-white text-slate-700 hover:border-blue-800 hover:text-blue-800" style={{padding: '4px 12px', fontSize: '11px'}}>Permissions</button><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-800" style={{padding: '4px 8px', fontSize: '11px'}}>Edit</button></div></div>
    <div className="flex items-center gap-2.5 border-b border-slate-100 py-2.5 last:border-b-0" style={{padding: '12px 0'}}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[11px] font-bold text-white [&_img]:h-full [&_img]:w-full [&_img]:rounded-full [&_img]:object-cover" style={{background: 'var(--ac)', width: '40px', height: '40px'}}><img src="https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=100&h=100&fit=crop" alt="CN"/></div><div><div className="text-[13px] font-semibold text-slate-800" style={{fontSize: '14px'}}>Pharm. Chidi Nwosu</div><div className="text-[11px] text-slate-400">Role B — Requesting Pharmacist · <span style={{color: 'var(--p)', fontWeight: '600'}}>LASUTH</span></div></div><div className="ml-auto flex gap-1.5"><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-emerald-50 text-emerald-700">Active</span><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-white text-slate-700 hover:border-blue-800 hover:text-blue-800" style={{padding: '4px 12px', fontSize: '11px'}}>Permissions</button><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-800" style={{padding: '4px 8px', fontSize: '11px'}}>Edit</button></div></div>
    <div className="flex items-center gap-2.5 border-b border-slate-100 py-2.5 last:border-b-0" style={{padding: '12px 0'}}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[11px] font-bold text-white [&_img]:h-full [&_img]:w-full [&_img]:rounded-full [&_img]:object-cover" style={{background: 'var(--ok)', width: '40px', height: '40px'}}><img src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=100&h=100&fit=crop" alt="FS"/></div><div><div className="text-[13px] font-semibold text-slate-800" style={{fontSize: '14px'}}>Dr. Funke Sotunde</div><div className="text-[11px] text-slate-400">Role C — Network Admin · <span style={{color: 'var(--p)', fontWeight: '600'}}>Ibadan</span></div></div><div className="ml-auto flex gap-1.5"><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-emerald-50 text-emerald-700">Active</span><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-white text-slate-700 hover:border-blue-800 hover:text-blue-800" style={{padding: '4px 12px', fontSize: '11px'}}>Permissions</button><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-800" style={{padding: '4px 8px', fontSize: '11px'}}>Edit</button></div></div>
    <div className="flex items-center gap-2.5 border-b border-slate-100 py-2.5 last:border-b-0" style={{padding: '12px 0'}}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[11px] font-bold text-white [&_img]:h-full [&_img]:w-full [&_img]:rounded-full [&_img]:object-cover" style={{background: 'var(--g400)', width: '40px', height: '40px'}}><img src="https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100&h=100&fit=crop" alt="ML"/></div><div><div className="text-[13px] font-semibold text-slate-800" style={{fontSize: '14px'}}>Dr. Musa Lawal</div><div className="text-[11px] text-slate-400">Role B — Requesting Pharmacist · <span style={{color: 'var(--p)', fontWeight: '600'}}>Lagos Island GH</span></div></div><div className="ml-auto flex gap-1.5"><span className="inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current before:content-[''] bg-amber-50 text-amber-700">Pending</span><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-white text-slate-700 hover:border-blue-800 hover:text-blue-800" style={{padding: '4px 12px', fontSize: '11px'}}>Permissions</button><button className="inline-flex cursor-pointer items-center gap-1.5 whitespace-nowrap rounded-lg border border-transparent px-3.5 py-2 text-[12.5px] font-semibold transition max-[768px]:w-full max-[768px]:justify-center [&_svg]:h-3.5 [&_svg]:w-3.5 [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-2 border-slate-200 bg-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-800" style={{padding: '4px 8px', fontSize: '11px'}}>Edit</button></div></div>
  </div>
    </div>
  );
}

export default UsersPage;
